### ISSUE TITLE
Requirements are quite high

### ISSUE THREAD

**Issue by Richtermeister** [spatie/db-dumper#1]
Hi there, 

I came across this lib as I was just about to start my own db-backup library.. I like what you did here a lot, however, I'm wondering why the requirements have to be so high (php7, symfony 3). It seems this lib does not really depend on process functionality that is not available in the ~2.7 range.. and the php7 syntax is neat, but also not really necessary (for performance or what not). Seems like 5.3+ would be just fine.

Either way, just curious, because as is I can't use this lib on older projects. Thank you for your time.

**Comment by freekmurze** [comment]
Hi, 

A few weeks ago I blogged [the reasons why we are requiring PHP 7 for our new packages](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/).

Of course, you are free to fork our code and create your own PHP 5 / Symfony 2 compatible fork. Opensource ftw!

**Comment by Richtermeister** [comment]
Hi @freekmurze, 

Cool, thanks for the reply, I had not read that blog yet, but I am subscribing now.

Rock on.

**Comment by freekmurze** [comment]
For some old projects I needed PHP 5.x compatibility myself. You'll be happy to learn that version 1.1.0 of the package adds support for PHP 5 / Symfony 2.X

**Comment by Richtermeister** [comment]
Awesome, very happy indeed. I think for a library such as this, it is the right choice. Thank you for letting me know.
