### ISSUE TITLE
syntax error, unexpected end of file db-dumper/src/DbDumper.php

### ISSUE THREAD

**Issue by menasoft** [spatie/db-dumper#101]
i have problem in backup database mysql 

error 
`local.ERROR: syntax error, unexpected end of file {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected end of file at /home/...vendor/spatie/db-dumper/src/DbDumper.php:279) [stacktrace] #0 /home/...vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/magic1/pu...') #1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\DbDumper...') #2 /home/...vendor/spatie/db-dumper/src/Databases/MySql.php(9): spl_autoload_call('Spatie\\\\DbDumper...') #3 /home/...vendor/composer/ClassLoader.php(444): include('/home/magic1/pu...') #4 /home/...vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/home/magic1/pu...') #5 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\DbDumper...') #6 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(51): spl_autoload_call('Spatie\\\\DbDumper...') #7 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/DbDumperFactory.php(25): Spatie\\Backup\\Tasks\\Backup\\DbDumperFactory::forDriver('mysql') #8 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(28): Spatie\\Backup\\Tasks\\Backup\\DbDumperFactory::createFromConnection('mysql') #9 /home/...vendor/laravel/framework/src/Illuminate/Support/Collection.php(1111): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::Spatie\\Backup\\Tasks\\Backup\\{closure}('mysql', 0) #10 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(29): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure)) #11 /home/...vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php(14): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::createDbDumpers(Array) #12 /home/...vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(27): Spatie\\Backup\\Tasks\\Backup\\BackupJobFactory::createFromArray(Array) #13 [internal function]: Spatie\\Backup\\Commands\\BackupCommand->handle() #14 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #15 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}() #16 /home/...vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure)) #17 /home/...vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL) #18 /home/...vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array) #19 /home/...vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle)) #20 /home/...vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle)) #21 /home/...vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #22 /home/...vendor/symfony/console/Application.php(908): Spatie\\Backup\\Commands\\BaseCommand->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #23 /home/...vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Spatie\\Backup\\Commands\\BackupCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #24 /home/...vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #25 /home/...vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #26 /home/...vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #27 /home/...artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #28 {main} "}`

**Comment by niekvanderkooy** [comment]
I was experiencing the same issue. Turns out, while my CLI was using PHP 7.3 and dumping worked, my server (where I was calling my artisan command) was still using PHP 7.2.
In other words: make sure you are using PHP 7.3 if you are trying to use the latest version of db-dumper

**Comment by menasoft** [comment]
i have already php higher version 7.2 on server can i use old version for db-dumper

**Comment by niekvanderkooy** [comment]
The requirement for 7.3 seems to have been introduced in 2.14.1, so specifying a version <= 2.14.0 file in your composer.json should work (2.14.0 requires PHP 7.1).

Although, it should be said, bumping the PHP requirement from 7.1 to 7.3 seems like a large change with regard to backwards compatibility for a minor db-dumper version increase, @freekmurze .

**Comment by freekmurze** [comment]
Normally composer will prevent you from using a package which requirements are not met.

Maybe you're using PHP 7.3 locally and 7.1 in production ? In that case, you should use the platform option. https://getcomposer.org/doc/06-config.md#platform

**Comment by niekvanderkooy** [comment]
I can't speak for @menasoft, but for me it was a server misconfiguration. The CLI was running 7.3 and correctly downloading the newest version, while the server was still running 7.2.

**Comment by Gummibeer** [comment]
@freekmurze it looks like PHP7.3 doesn't follow the warnings in the official PHP doc.
https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc
> It is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;). That means especially that the identifier may not be indented

https://github.com/spatie/db-dumper/blob/093750d69c383fb14d9e7cd6caa052ea7b35e5b5/src/DbDumper.php#L265-L273
The whole block is indented - so following the docs this isn't allowed. Even if PHP7.3 seems to ignore this.

**Comment by freekmurze** [comment]
@brendt can you take a look at this?

**Comment by brendt** [comment]
@Gummibeer wasn't this behaviour changed in 7.3? https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

I believe the docs are simply outdated, because this was an explicit new feature in 7.3

**Comment by Gummibeer** [comment]
@brendt ok, this would clarify why it works in PHP7.3 (you require) and not in 7.2. 😄
