### ISSUE TITLE
People? Why minor version requires PHP 7.3 

### ISSUE THREAD

**Issue by prialgauskaslt** [spatie/db-dumper#102]
Please gimme logic here. 
**2.14.0** - PHP 7.1. 
**2.14.1** -  PHP 7.3

......

https://github.com/spatie/db-dumper/blob/c9b699c74b56adeff75da76cef8a82a8529765ad/composer.json#L22

**Comment by freekmurze** [comment]
Upping requirements is not a breaking change according to semver. The public API did not change. If you don't agree, please read the semver specification (https://semver.org/) and point me to the rule that we broke.

**Comment by prialgauskaslt** [comment]
I understand and follow "spatie way" for upgrading to every new PHP version. But if we tag minor version, we hope that composer update will not make maintaining project more extensive - basically upgrading the dependences (in this case - PHP) which would in return force maintainers of the project to go through all packages and upgrading them for compatibility with PHP dependecy. 

As for semver - yes, I understand your argument, so I can not blame anyone but myself. But I just hoped for minor version bump in PHP version requirement bumps though spatie packages iterations.

Thank you for working on such a great projects. Cheers.

**Comment by freekmurze** [comment]
> p.s. It would be nice to see such changes at least in Release description.

That's a good suggestion. In most packages we do this, in this case, it was forgotten, I'll add it! 👍
