### ISSUE TITLE
Connections via proxy

### ISSUE THREAD

**Issue by stebogit** [spatie/db-dumper#108]
Hi,
our app is using `DbDumper` to regularly update a local copy of a remote database. Recently we moved our app to Heroku, which doesn't provide a static IP, so we can't set a specific IP in the allowed hosts accessing the remote DB.
[FIXIE](https://elements.heroku.com/addons/fixie) though is an add-on that [provides a proxy](https://devcenter.heroku.com/articles/fixie#using-with-php) for your app when you need a static IP (we already use it for http requests).
However I don't know if it is possible to use that proxy (particularly the auth part ) for a `mysqldump` command.
If it was possible, I could probably tweak `DbDumper` [here](https://github.com/spatie/db-dumper/blob/master/src/Databases/MySql.php#L289-L300) to use different credentials for the client, but I would not know how the correct command should look like.

Would something like this work?
```php
public function getContentsOfCredentialsFile(): string
{
    $fixieUrl = getenv("FIXIE_URL"); // something like http://fixie:1234somestring@velodrome.usefixie.com:80
    $parsedFixieUrl = parse_url($fixieUrl);
    
    $contents = [
        '[client]',
        "user = '{$parsedFixieUrl['user']}'",
        "password = '{$parsedFixieUrl['pass']}'",
        "host = '{$parsedFixieUrl['host']}'",
        "port = '{$parsedFixieUrl['port']}'",
    ];

    return implode(PHP_EOL, $contents);
}
```
Thanks

**Comment by atymic** [comment]
From the `Fixie` docs: 

> Static` IP addresses for outbound HTTP and HTTPS requests

I'm pretty sure you can't connect to a mysql server over a HTTP(s) proxy.
I'd suggest you create a SSH tunnel (if possible) and then you can dump like so:

```php
Spatie\DbDumper\Databases\MySql::create()
    ->setDbName($databaseName)
    ->setHost('127.0.0.1')
    ->setPort(5555) // SSH tunnel port
    ->setUserName($userName)
    ->setPassword($password)
    ->dumpToFile('dump.sql');
```
