### ISSUE TITLE
Memory leak when dumping with compression enabled

### ISSUE THREAD

**Issue by vdbelt** [spatie/db-dumper#109]
PR https://github.com/spatie/db-dumper/pull/100 seems to have introduced a memory leak, which causes backups to fail on machines that have a mysql data dir larger than the available amount of memory / swap space. 

Wrapping the output in an if, will store the entire uncompressed dump in a temporary variable which takes up huge amounts of RAM (as opposed to directly streaming to gzip in earlier versions).

I reproduced this with setting up a new machine with a limited amount of memory, seeding MySQL with a large enough amount of data, and using spatie/laravel-backup to dump the data to disk.

With spatie/db-dumper:2.14.2, the `backup:run --only-db` command will run without errors, but produces an empty dump file. Downgrading to 2.14.0 generates a perfectly working dump:

`martin@debian:~/app/storage/app/Laravel$ ls -lah`
`-rw-r--r-- 1 martin martin  175 Jul 24 11:54 2019-07-24-11-54-10.zip` (2.14.2)
`-rw-r--r-- 1 martin martin  85M Jul 24 11:56 2019-07-24-11-56-07.zip` (2.14.0)

Monitoring `watch -n 1 free -m` while the dump is in progress, confirms that the machine is rapidly running out of memory.

**Comment by vdbelt** [comment]
Some possible solutions for a fix:

- Remove the wrapper, and do a check whether the mysqldump executable exists prior to running the dump. This would still cause empty gz dumps if mysqldump were to fail for any other reason, but mitigates user configuration errors as originally mentioned in #89.
- Temporarily store the uncompressed dump on disk, verify it, and running gzip on the dump afterwards.
- Separating the dump and gzip commands, by leveraging the streaming/piping capabilities of `symfony/process`, and catching errors on mysqldump while concurrently gzipping the stream. Might introduce some additional complexity to implementation, and I'm not sure how this would do performance wise.

Additionally, I think an exception should be thrown if the file size of the gzipped dump is arbitrary low.

Happy to look at a PR.

**Comment by freekmurze** [comment]
Please do send a PR for this 👍

**Comment by fgilio** [comment]
I guess this issue can be closed now 🎉
