### ISSUE TITLE
restore after a backup ?

### ISSUE THREAD

**Issue by imard28** [spatie/db-dumper#115]

**Comment by atymic** [comment]
Can you provide some more context?

It's pretty simple to restore a DB dump, just execute the SQL against the database.

**Comment by imard28** [comment]
Yes, but I mean automatically restore the db and the files that were backed up.

I am implementing an update system for my Laravel app and before updating I will make a backup with this package, in case an error occurs after updating I could restore the previous version of both the files and the db, is it possible to do this automatically?

**Comment by atymic** [comment]
It's not supported by this package. I'd say automated rollbacks are probably out of scope of this project as well. You'll probably need to build something custom.
