### ISSUE TITLE
There is no way to customize mysql.socket option

### ISSUE THREAD

**Issue by dakshhmehta** [spatie/db-dumper#121]
Recently, I am handling a server powered with Bitnami AMI on EC2 instance.

The path to mysql.socket is to /opt/bitnami/mysql/tmp/mysql.socket or something in there.

The dumper always wants the file to be present in /tmp folder at root level.

However, I see there has to be option to customize the option for the following line in Mysql.php class
https://github.com/spatie/db-dumper/blob/61583b9b5631433674f7c1dfb95cd94ed79556b9/src/Databases/MySql.php#L257

I found this issue while using the spatie/laravel-backup package.

**Comment by freekmurze** [comment]
I don't understand the issue. There clearly is a way to specify a custom socket.

If the package does something wrong, please submit a PR.

**Comment by dakshhmehta** [comment]
Apology for bad explimation

Basically, when we install a default LAMP install, the mysql.socket file is created at /tmp/mysql.socket and when we use bitnami AMI (https://docs.bitnami.com/aws/infrastructure/lamp/) because the mysql is installed at /opt/bitnami/mysql/tmp/mysql.socket

Also, to fix the issue, laravel has .env DB_SOCKET variable which should be used I think...

I will try sending PR.
