### ISSUE TITLE
Error when using the compressor under Windows

### ISSUE THREAD

**Issue by thomasgabler** [spatie/db-dumper#122]
Hi, 
there is a problem when using the compressor in Windows: 
In the function echoToFile: 
`return "(((({$command}; echo \$? >&3) | {$compressCommand} > {$dumpFile}) 3>&1) | (read x; exit \$x))";`
- ";" does not work under Windows ("&") and 
- "read" function does not exist 

see enclosed patch 
[Windows.patch.txt](https://github.com/spatie/db-dumper/files/3992278/Windows.patch.txt)

With kind regards 
Thomas

**Comment by riasvdv** [comment]
Could you send a PR that fixes this?
