### ISSUE TITLE
Question about remote database 

### ISSUE THREAD

**Issue by quentingosset** [spatie/db-dumper#128]
Hello, I am currently facing a small problem.
I use a docker environment with NGNINX and MariaDB on 2 different containers.
I need from my web application to make a backup of a database on my MariaDB so I try your module and I get the following error:
`"The dump process failed with exitcode 127: Command not found: sh: 1: mysqldump: not found"`

I suppose you are using a command (mysqldump) directly on the server to access the remote database server. however, being on docker, the application runs on the NGINX container which therefore does not have the mysqldump command and therefore cannot connect. Do you have a solution to resolve concerns?

I currently use this library: https://github.com/ifsnop/mysqldump-php however I find your library much more ergonomic and I would therefore like to know if there was a way to do what I need with your library.

Thank you

**Comment by theonelucas** [comment]
Just use the `setHost` method with the name of your docker service.

`MySql::create()->setHost(env('DB_HOST'))`

**Comment by albertpratomo** [comment]
Using `setHost` doesn't solve the problem, `mysqldump` is still not found.
