### ISSUE TITLE
Separate .sql files for each table

### ISSUE THREAD

**Issue by mattiasgeniar** [spatie/db-dumper#13]
Hi Freek!

Would you be interested in a patch that would store each table of a database in a separate file? Instead of a single .sql result, it would be one file for each table.

It can be more convenient for (partial) restores, but the destination directory may get crowded with files - zip'ing them up afterwards is probably going to be a requirement.

If it's a feature you're considering, I'll look into making a PR. The idea was to have this (optionally) be included in [spatie/laravel-backup](https://github.com/spatie/laravel-backup).

Mattias

**Comment by freekmurze** [comment]
That's a very good suggestion. I plan on creating a new major version of this package in tandem with a new major version for laravel-backup. 

So I think there's no need to create a PR for the current version, but I'll be sure to include this functionality in v2 of db-dumper (and integrated in laravel-backup v4).

**Comment by mattiasgeniar** [comment]
Nice!

I see 2 practical methods of doing so;

- in PHP: 'SHOW TABLES;' query and loop each with a custom ```mysqldump``` command
- a shell implementation, which loops the output of ```mysql``` and starts a mysqldump for each table ([example](https://www.jamescoyle.net/how-to/1167-export-mysql-database-into-separate-files-per-table))

Option 1 has the benefit of being a pure PHP implementation, but requires a connection to be made from db-dumper to the database, something which wasn't necessary for now.

Option 2 has the benefit that it's a pure "bash like" implementation, without PHP directly accessing the DB (although I'm assuming that would/should never be an issue).

It would look like option 1 is probably the better path to take.

**Comment by freekmurze** [comment]
On first thought option 1 has my preference too. Will investigate further when starting work on the new major versions.

**Comment by freekmurze** [comment]
V2 of this package has been tagged. I'd accept a non breaking PR with tests that adds dumping to separate .sql files for each table to the package.

**Comment by freekmurze** [comment]
Closing this for now. If anybody can implement this in a clean, readable way, I'd probably accept a PR.
