### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by aminladhari** [spatie/db-dumper#131]
Class 'App\Console\Commands\Spatie\DbDumper\Databases\MySql' Not Found

php version 7.2.19
composer 1.8.6
Laravel 5.7.29
"spatie/db-dumper": "^2.16",
the command source code : 
![db-dumper](https://user-images.githubusercontent.com/18463676/84962038-15b00a00-b106-11ea-8855-25e7a80e103c.png)

**Comment by mehedi-iitdu** [comment]
Did you solve the issue?

**Comment by noahheck** [comment]
It looks like you are missing your leading `\` in the call to the `Spatie\DbDumper\Databases\MySql::create()`. Add the leading `\` and you should be ok, or, since you've imported the class above, you should be able to reduce this to `MySql::create()`.
