### ISSUE TITLE
The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by minhhoangtgg** [spatie/db-dumper#137]
The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command, operable program or batch file. 
Please help me.

**Comment by edalzell** [comment]
Is your mysql local or in Docker?

**Comment by jpswade** [comment]
You don't have mysqldump installed on your system. What system are you using?

**Comment by oriceon** [comment]
Have same issue on Windows 10.
