### ISSUE TITLE
Misuse of shell builtins :  {"exception":"[object] 

### ISSUE THREAD

**Issue by tahirkeskin** [spatie/db-dumper#154]
Hi,

My Code;

\Spatie\DbDumper\Databases\MySql::create()
                    ->setDbName($information['db_name'])
                    ->setUserName($information['mysql_user'])
                    ->setPassword($information['mysql_password'])
                    ->setHost($information['server_ip'])
                    ->setPort($information['mysql_port'])
                    ->addExtraOption('--single-transaction')
                    ->useCompressor(new \Spatie\DbDumper\Compressors\GzipCompressor())
                    ->dumpToFile($information['path']);

The error I get when trying to get dump. I can't see the details of the error. ({"exception":"**[object]**)

The dump process failed with exitcode 2 : Misuse of shell builtins

laravel.log Error;

local.ERROR: The dump process failed with exitcode 2 : Misuse of shell builtins :  {"exception":"[object] (Spatie\\DbDumper\\Exceptions\\Dump>
[stacktrace]
#0 /var/www/site.local/vendor/spatie/db-dumper/src/DbDumper.php(263): Spatie\\DbDumper\\Exceptions\\DumpFailed::processDidNotEndSuccessfully()
#1 /var/www/site.local/vendor/spatie/db-dumper/src/Databases/MySql.php(203): Spatie\\DbDumper\\DbDumper->checkIfDumpWasSuccessFul()
#2 /var/www/site.local/app/Jobs/CreateAutoBackup.php(96): Spatie\\DbDumper\\Databases\\MySql->dumpToFile()
#3 /var/www/site.local/app/Jobs/CreateAutoBackup.php(46): App\\Jobs\\CreateAutoBackup->startDump()
#4 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\CreateAutoBackup->handle()
#5 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\>
#6 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod>
#8 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#10 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closur>
#11 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\>
#12 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#13 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#14 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Que>
#15 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\>
#16 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#17 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchTh>
#18 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#19 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(414): Illuminate\\Queue\\Jobs\\Job->fire()
#20 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(364): Illuminate\\Queue\\Worker->process()
#21 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#22 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#23 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runW>
#24 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#25 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container>
#26 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#27 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMetho>
#28 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#29 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#30 /var/www/site.local/vendor/symfony/console/Command/Command.php(288): Illuminate\\Console\\Command->execute()
#31 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#32 /var/www/site.local/vendor/symfony/console/Application.php(974): Illuminate\\Console\\Command->run()
#33 /var/www/site.local/vendor/symfony/console/Application.php(291): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/site.local/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#36 /var/www/site.local/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#37 /var/www/site.local/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}
"}

Would you check? Thanks.

**Comment by tahirkeskin** [comment]
"spatie/db-dumper": "^2.21"

**Comment by tahirkeskin** [comment]
I tested it again. The situation has nothing to do with compression. I'm getting the same error. It is outputting the error as [object]. And you can't see that. If you value your project, I recommend not using such 3rd party packages if possible.

**Comment by tahirkeskin** [comment]
After a long struggle, I found the source of the problem. The problem is because there are data in the database that do not conform to utf-8.

**Comment by stebogit** [comment]
Hey @tahirkeskin what MySQL (thus `mysqldump`) version are you using? Is `utf-8` a requirement of MySQL 8?
I get a similar error connecting to an external DB that used to be MySQL 5.7 and was just now updated to v8.

> [Sep 24 02:02:31]: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2026: SSL connection error: unknown error number when trying to connect
> [Sep 24 02:02:31]: [2021-09-24 02:02:31] stack.ERROR: The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2026: SSL connection error: unknown error number when trying to connect

Using `spatie/db-dumper` v2.18

**Comment by tahirkeskin** [comment]
Hi @stebogit,

Sorry for the late conversion. I'm using MySQL 8.0.25. Charset settings are very important MySQL databases. Problems with charset when importing dump are one of the common problems. But looking at your mistake, I don't think there is a problem with charset. Can you try the solutions below? I think it can solve your problem.

https://stackoverflow.com/questions/61649764/mysql-error-2026-ssl-connection-error-ubuntu-20-04

Have a nice working day! :)

**Comment by stebogit** [comment]
Thanks @tahirkeskin in my case updating to MySQL 8 fixed the issue
