### ISSUE TITLE
dump only structure each table

### ISSUE THREAD

**Issue by jazz7381** [spatie/db-dumper#155]
How can i dump only structure for each table without its data?

**Comment by tahirkeskin** [comment]
Hi,

If you add the following option, your problem will be solved.

->addExtraOption('--no-data')

Example;

Spatie\DbDumper\Databases\MySql::create()
    ->setDbName($databaseName)
    ->setUserName($userName)
    ->setPassword($password)
    ->addExtraOption('--no-data')
    ->dumpToFile('dump.sql');

Have a nice day!
