### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by Jamesking56** [spatie/db-dumper#2]
Hello,

It would be great if this package supported other DBs.

I can add a Postgres dumper if you like, maybe also a SQLite one if you require. MSSQL could be useful for some people too.

Would be also nice if you had the same databases supported as Laravel Framework.

**Comment by freekmurze** [comment]
I only need MySQL for my projects, so that is the only one that comes out of the box. 

I'd accept pull requests that add other db's. Just make sure you make the new dumpers extend [the `DbDumper`-class](https://github.com/spatie/db-dumper/blob/master/src/DbDumper.php).

**Comment by Jamesking56** [comment]
@freekmurze I can see you've added PostgreSQL...

**Comment by freekmurze** [comment]
Yup, another user contributed it.
