### ISSUE TITLE
Extra Options for Laravel-Backup version 5.2

### ISSUE THREAD

**Issue by rafwell** [spatie/db-dumper#23]
Hi, i'm using your package laravel-backup in laravel 5.2 and for backup procedures i need put a new parameter `--routines` for mysqldump. In your lastest version it work using "extra_options". I've tried add this feature in 1.5.2 tag, but i cannot create a PR from this tag ( i dont know why, i1m newbie in git world).

So, this is my commit: https://github.com/rafwell/db-dumper/commit/c69901fb8523aaf59bf7f5b5b2a6e6b28fe27324 i'm using this tag (1.5.2) in my projects and work fine.

Can you help me how create the pr or merge to your repo? Thanks.

See https://github.com/spatie/laravel-backup/pull/315

**Comment by freekmurze** [comment]
`v1` of this package is not supported anymore. Please use `v2` where you can set all the custom options you want.
