### ISSUE TITLE
Gzip dump file

### ISSUE THREAD

**Issue by afraca** [spatie/db-dumper#35]
Both adminer and phpmyadmin support compressing the dump files with gzip. Any of you have any thoughts on this? I'm not sure how they achieve it, I think they use gzencode/gzdecode in PMA.

**Comment by freekmurze** [comment]
This package is primarily used in [our backup package](https://github.com/spatie/laravel-backup). That package will zip the dumped file together will all other files that need to be backed up.

If you want to manually zip the dumpfile, you can use PHP's standard `Zip` class (or use a command line tool to zip files).
