### ISSUE TITLE
db-dumper makes an empty file if there is no mysqldump installed

### ISSUE THREAD

**Issue by nanofelix** [spatie/db-dumper#55]
If there is not mysqldump installed on the system, db-dumper will make and empty dump file. 
CLI console will output nothing.

**Comment by freekmurze** [comment]
If `mysqldump` is not present a warning will be given.

![screen shot 2017-06-19 at 20 05 10](https://user-images.githubusercontent.com/483853/27298844-89cdad9c-552a-11e7-8b9d-9d6ac9b194f1.jpg)
