### ISSUE TITLE
Reconsider "Added `--databases` option before DB name"

### ISSUE THREAD

**Issue by orottier** [spatie/db-dumper#57]
Refering to https://github.com/spatie/db-dumper/pull/56

By adding the `--databases` option to mysqldump, the dump file is prepended with
```
CREATE DATABASE /*!32312 IF NOT EXISTS*/ `my_database` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `my_database`;
```

which is rather inconvenient if you want to use the dump to fill another database, e.g. this does not work anymore
```
mysql -u user -p... other_database < db-dumps/mysql-my_database.sql
```

I understand the reasons @rodrigopedra has for adding the flag but I would like it to be optional and maybe non-default as this is possibly a breaking change. Let me know what you think!

**Comment by orottier** [comment]
Well that was quick!
Looks good to me, I've tested it and it has the original default behaviour 👍

**Comment by freekmurze** [comment]
We'll handle this further in #58
