### ISSUE TITLE
Exclude tables content not structure

### ISSUE THREAD

**Issue by oriceon** [spatie/db-dumper#77]
Hi. There is a way to exclude table content, not table structure?
Because some time you need to skip content not both (structure and content).

On a batch file, i`m using next code and is workin`:

```code
mysqldump --single-transaction --add-drop-table --no-data --databases db_name > exclude.sql
mysqldump --single-transaction --no-create-info --ignore-table=database.table1 --ignore-table=database.table2 --databases db_name >> exclude.sql
```

Can you implement please some behaviour like that?

Thank you.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that adds this behaviour to the package.
