### ISSUE TITLE
Error: postgresql backup Windows 10

### ISSUE THREAD

**Issue by n1ghtl1z4rd** [spatie/db-dumper#87]
Not working:
https://s.mail.ru/Ab1H/AejpxqCtd
https://s.mail.ru/DbkV/BJcwU8Je5

Working:
https://s.mail.ru/EFWK/Wwinnsmj1
https://s.mail.ru/EGja/t7jooxjow

**Comment by freekmurze** [comment]
There is too little here to go. Please track down the exact error yourself. If you find out the package is in error, please submit a failing test for me to fix.

**Comment by n1ghtl1z4rd** [comment]
Testing started at 14:10 ...
C:\Server\php\php.exe C:/Server/sites/nlCMS/www/vendor/phpunit/phpunit/phpunit --no-configuration Spatie\DbDumper\Test\PostgreSqlTest C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php --teamcity
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:36 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 | gzip > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 | gzip > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:49 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 | gzip > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 | gzip > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:62 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 | gzip > "/save/to/new (directory)/dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 | gzip > "/save/to/new (directory)/dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:75 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 --inserts > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 --inserts > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:88 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 1234 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 1234 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:101 

Failed asserting that two strings are identical.
Expected :''/custom/directory/pg_dump' -U username -h localhost -p 5432 > "dump.sql"'
Actual   :'/custom/directory/pg_dump -U username -h localhost -p 5432 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:114 

Failed asserting that two strings are equal.
Expected :''pg_dump' -U username -h /var/socket.1234 -p 5432 > "dump.sql"'
Actual   :'pg_dump -U username -h /var/socket.1234 -p 5432 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:127
 
Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 -t tb1 -t tb2 -t tb3 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 -t tb1 -t tb2 -t tb3 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:140 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 -t tb1 -t tb2 -t tb3 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 -t tb1 -t tb2 -t tb3 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:153
 
Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 -T tb1 -T tb2 -T tb3 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 -T tb1 -T tb2 -T tb3 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:179 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 -T tb1 -T tb2 -T tb3 > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 -T tb1 -T tb2 -T tb3 > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:192 

Failed asserting that two strings are identical.
Expected :''pg_dump' -U username -h localhost -p 5432 -something-else > "dump.sql"'
Actual   :'pg_dump -U username -h localhost -p 5432 -something-else > "dump.sql"'
 <Click to see difference>
 C:\Server\sites\nlCMS\www\tests\Unit\PostgreSqlTest.php:242

Time: 133 ms, Memory: 6.00MB
FAILURES!
Tests: 20, Assertions: 20, Failures: 13.
Process finished with exit code 1
