### ISSUE TITLE
Error after 2.13.0 update

### ISSUE THREAD

**Issue by neochief** [spatie/db-dumper#94]
When I run php artisan backup:run, I get following error:
```
Starting backup...
Dumping database refactoring...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: set: Illegal option -o pipefail
.
#0 /home/forge/.../vendor/spatie/db-dumper/src/DbDumper.php(246): Spatie\DbDumper\Exceptions\DumpFailed::processDidNotEndSuccessfully(Object(Symfony\Component\Process\Process))
...
...
```

Everything works just fine under 2.12

This is most likely related to the recent pull request https://github.com/spatie/db-dumper/pull/91

Btw, I use default Ubuntu 18 on forge.

**Comment by rubenvanassche** [comment]
@neochief Ubuntu is using dash instead of bash for executing commands. Dash doesn't support the pipefail operator we're using to detect errors in the dumping of the database. I'm looking into a solution to fix this problem.

**Comment by neochief** [comment]
Thanks for the info!

**Comment by rubenvanassche** [comment]
We've just tagged db-dumper 2.13.1 which reverts the changes. Next week I will work on a better solution for the problem which will not use pipefails.
